global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'jewelry_processor'
    static_configs:
      - targets: ['web:5000', 'worker:5000']
    metrics_path: '/metrics'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'process_.*'
        action: keep

  - job_name: 'model_metrics'
    static_configs:
      - targets: ['worker:5000']
    metrics_path: '/model-metrics'
    scrape_interval: 30s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'