name: Deploy Kubernetes Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate with GKE
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Apply Namespace
        run: |
          kubectl apply -f kubernetes/namespace.yaml

      - name: Apply ConfigMap
        run: |
          kubectl apply -f kubernetes/configmap.yaml

      - name: Apply Secrets
        run: |
          kubectl apply -f kubernetes/secrets.yaml

      - name: Apply Persistent Volume Claims
        run: |
          kubectl apply -f kubernetes/persistent-volume-claims.yaml

      - name: Apply Storage Class
        run: |
          kubectl apply -f kubernetes/storage-class.yaml

      - name: Apply Deployments
        run: |
          kubectl apply -f kubernetes/web-deployment.yaml
          kubectl apply -f kubernetes/worker-deployment.yaml

      - name: Apply Services
        run: |
          kubectl apply -f kubernetes/services.yaml

      - name: Apply Ingress
        run: |
          kubectl apply -f kubernetes/ingress.yaml

      - name: Verify Resources
        run: |
          kubectl get all -n your-namespace
