name: Lint Workflows

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install actionlint
        run: |
          curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/install.sh | bash
          sudo mv actionlint /usr/local/bin/

      - name: Lint Workflows
        run: actionlint .github/workflows/
